/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse20015DefCurrency : IEquatable<InlineResponse20015DefCurrency>
    { 
        /// <summary>
        /// Gets or Sets CurrencyId
        /// </summary>
        [DataMember(Name="CurrencyId")]
        public int? CurrencyId { get; set; }

        /// <summary>
        /// Gets or Sets RoundingType
        /// </summary>
        [DataMember(Name="RoundingType")]
        public int? RoundingType { get; set; }

        /// <summary>
        /// Gets or Sets NoofDecimals
        /// </summary>
        [DataMember(Name="NoofDecimals")]
        public int? NoofDecimals { get; set; }

        /// <summary>
        /// Gets or Sets Symbol
        /// </summary>
        [DataMember(Name="Symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or Sets GeneralRoundOff
        /// </summary>
        [DataMember(Name="GeneralRoundOff")]
        public int? GeneralRoundOff { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20015DefCurrency {\n");
            sb.Append("  CurrencyId: ").Append(CurrencyId).Append("\n");
            sb.Append("  RoundingType: ").Append(RoundingType).Append("\n");
            sb.Append("  NoofDecimals: ").Append(NoofDecimals).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  GeneralRoundOff: ").Append(GeneralRoundOff).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse20015DefCurrency)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse20015DefCurrency instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse20015DefCurrency to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20015DefCurrency other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CurrencyId == other.CurrencyId ||
                    CurrencyId != null &&
                    CurrencyId.Equals(other.CurrencyId)
                ) && 
                (
                    RoundingType == other.RoundingType ||
                    RoundingType != null &&
                    RoundingType.Equals(other.RoundingType)
                ) && 
                (
                    NoofDecimals == other.NoofDecimals ||
                    NoofDecimals != null &&
                    NoofDecimals.Equals(other.NoofDecimals)
                ) && 
                (
                    Symbol == other.Symbol ||
                    Symbol != null &&
                    Symbol.Equals(other.Symbol)
                ) && 
                (
                    GeneralRoundOff == other.GeneralRoundOff ||
                    GeneralRoundOff != null &&
                    GeneralRoundOff.Equals(other.GeneralRoundOff)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CurrencyId != null)
                    hashCode = hashCode * 59 + CurrencyId.GetHashCode();
                    if (RoundingType != null)
                    hashCode = hashCode * 59 + RoundingType.GetHashCode();
                    if (NoofDecimals != null)
                    hashCode = hashCode * 59 + NoofDecimals.GetHashCode();
                    if (Symbol != null)
                    hashCode = hashCode * 59 + Symbol.GetHashCode();
                    if (GeneralRoundOff != null)
                    hashCode = hashCode * 59 + GeneralRoundOff.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse20015DefCurrency left, InlineResponse20015DefCurrency right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse20015DefCurrency left, InlineResponse20015DefCurrency right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
