/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse20017Data : IEquatable<InlineResponse20017Data>
    { 
        /// <summary>
        /// Gets or Sets ViewID
        /// </summary>
        [DataMember(Name="View__ID")]
        public int? ViewID { get; set; }

        /// <summary>
        /// Gets or Sets ViewName
        /// </summary>
        [DataMember(Name="View__Name")]
        public string ViewName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20017Data {\n");
            sb.Append("  ViewID: ").Append(ViewID).Append("\n");
            sb.Append("  ViewName: ").Append(ViewName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse20017Data)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse20017Data instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse20017Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20017Data other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ViewID == other.ViewID ||
                    ViewID != null &&
                    ViewID.Equals(other.ViewID)
                ) && 
                (
                    ViewName == other.ViewName ||
                    ViewName != null &&
                    ViewName.Equals(other.ViewName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ViewID != null)
                    hashCode = hashCode * 59 + ViewID.GetHashCode();
                    if (ViewName != null)
                    hashCode = hashCode * 59 + ViewName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse20017Data left, InlineResponse20017Data right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse20017Data left, InlineResponse20017Data right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
