/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse2005Data : IEquatable<InlineResponse2005Data>
    { 
        /// <summary>
        /// Gets or Sets MasterId
        /// </summary>
        [DataMember(Name="MasterId")]
        public int? MasterId { get; set; }

        /// <summary>
        /// Gets or Sets VoucherNo
        /// </summary>
        [DataMember(Name="VoucherNo")]
        public string VoucherNo { get; set; }

        /// <summary>
        /// Gets or Sets Exception
        /// </summary>
        [DataMember(Name="Exception")]
        public string Exception { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2005Data {\n");
            sb.Append("  MasterId: ").Append(MasterId).Append("\n");
            sb.Append("  VoucherNo: ").Append(VoucherNo).Append("\n");
            sb.Append("  Exception: ").Append(Exception).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse2005Data)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse2005Data instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2005Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2005Data other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MasterId == other.MasterId ||
                    MasterId != null &&
                    MasterId.Equals(other.MasterId)
                ) && 
                (
                    VoucherNo == other.VoucherNo ||
                    VoucherNo != null &&
                    VoucherNo.Equals(other.VoucherNo)
                ) && 
                (
                    Exception == other.Exception ||
                    Exception != null &&
                    Exception.Equals(other.Exception)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MasterId != null)
                    hashCode = hashCode * 59 + MasterId.GetHashCode();
                    if (VoucherNo != null)
                    hashCode = hashCode * 59 + VoucherNo.GetHashCode();
                    if (Exception != null)
                    hashCode = hashCode * 59 + Exception.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse2005Data left, InlineResponse2005Data right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse2005Data left, InlineResponse2005Data right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
