/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse20021Data : IEquatable<InlineResponse20021Data>
    { 
        /// <summary>
        /// Gets or Sets BinsDetails
        /// </summary>
        [DataMember(Name="BinsDetails")]
        public List<InlineResponse20021BinsDetails> BinsDetails { get; set; }

        /// <summary>
        /// Gets or Sets ProductData
        /// </summary>
        [DataMember(Name="ProductData")]
        public List<InlineResponse20021ProductData> ProductData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20021Data {\n");
            sb.Append("  BinsDetails: ").Append(BinsDetails).Append("\n");
            sb.Append("  ProductData: ").Append(ProductData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse20021Data)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse20021Data instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse20021Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20021Data other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BinsDetails == other.BinsDetails ||
                    BinsDetails != null &&
                    BinsDetails.SequenceEqual(other.BinsDetails)
                ) && 
                (
                    ProductData == other.ProductData ||
                    ProductData != null &&
                    ProductData.SequenceEqual(other.ProductData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BinsDetails != null)
                    hashCode = hashCode * 59 + BinsDetails.GetHashCode();
                    if (ProductData != null)
                    hashCode = hashCode * 59 + ProductData.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse20021Data left, InlineResponse20021Data right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse20021Data left, InlineResponse20021Data right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
