/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse20020Data : IEquatable<InlineResponse20020Data>
    { 
        /// <summary>
        /// Gets or Sets ModuleId
        /// </summary>
        [DataMember(Name="ModuleId")]
        public int? ModuleId { get; set; }

        /// <summary>
        /// Gets or Sets ScreenId
        /// </summary>
        [DataMember(Name="ScreenId")]
        public int? ScreenId { get; set; }

        /// <summary>
        /// Gets or Sets AlertPurpose
        /// </summary>
        [DataMember(Name="AlertPurpose")]
        public string AlertPurpose { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name="Count")]
        public int? Count { get; set; }

        /// <summary>
        /// Gets or Sets ScreenName
        /// </summary>
        [DataMember(Name="ScreenName")]
        public string ScreenName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20020Data {\n");
            sb.Append("  ModuleId: ").Append(ModuleId).Append("\n");
            sb.Append("  ScreenId: ").Append(ScreenId).Append("\n");
            sb.Append("  AlertPurpose: ").Append(AlertPurpose).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  ScreenName: ").Append(ScreenName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse20020Data)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse20020Data instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse20020Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20020Data other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ModuleId == other.ModuleId ||
                    ModuleId != null &&
                    ModuleId.Equals(other.ModuleId)
                ) && 
                (
                    ScreenId == other.ScreenId ||
                    ScreenId != null &&
                    ScreenId.Equals(other.ScreenId)
                ) && 
                (
                    AlertPurpose == other.AlertPurpose ||
                    AlertPurpose != null &&
                    AlertPurpose.Equals(other.AlertPurpose)
                ) && 
                (
                    Count == other.Count ||
                    Count != null &&
                    Count.Equals(other.Count)
                ) && 
                (
                    ScreenName == other.ScreenName ||
                    ScreenName != null &&
                    ScreenName.Equals(other.ScreenName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ModuleId != null)
                    hashCode = hashCode * 59 + ModuleId.GetHashCode();
                    if (ScreenId != null)
                    hashCode = hashCode * 59 + ScreenId.GetHashCode();
                    if (AlertPurpose != null)
                    hashCode = hashCode * 59 + AlertPurpose.GetHashCode();
                    if (Count != null)
                    hashCode = hashCode * 59 + Count.GetHashCode();
                    if (ScreenName != null)
                    hashCode = hashCode * 59 + ScreenName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse20020Data left, InlineResponse20020Data right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse20020Data left, InlineResponse20020Data right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
