/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Model8APIMastersCoreWarehouseData : IEquatable<Model8APIMastersCoreWarehouseData>
    { 
        /// <summary>
        /// Gets or Sets SCode
        /// </summary>
        [DataMember(Name="sCode")]
        public string SCode { get; set; }

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [DataMember(Name="Alias")]
        public string Alias { get; set; }

        /// <summary>
        /// Gets or Sets SName
        /// </summary>
        [DataMember(Name="sName")]
        public string SName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Model8APIMastersCoreWarehouseData {\n");
            sb.Append("  SCode: ").Append(SCode).Append("\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  SName: ").Append(SName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Model8APIMastersCoreWarehouseData)obj);
        }

        /// <summary>
        /// Returns true if Model8APIMastersCoreWarehouseData instances are equal
        /// </summary>
        /// <param name="other">Instance of Model8APIMastersCoreWarehouseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Model8APIMastersCoreWarehouseData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SCode == other.SCode ||
                    SCode != null &&
                    SCode.Equals(other.SCode)
                ) && 
                (
                    Alias == other.Alias ||
                    Alias != null &&
                    Alias.Equals(other.Alias)
                ) && 
                (
                    SName == other.SName ||
                    SName != null &&
                    SName.Equals(other.SName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SCode != null)
                    hashCode = hashCode * 59 + SCode.GetHashCode();
                    if (Alias != null)
                    hashCode = hashCode * 59 + Alias.GetHashCode();
                    if (SName != null)
                    hashCode = hashCode * 59 + SName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Model8APIMastersCoreWarehouseData left, Model8APIMastersCoreWarehouseData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Model8APIMastersCoreWarehouseData left, Model8APIMastersCoreWarehouseData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
