/*
 * API Documentation
 *
 * defaultDeription
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Model8APITransactionsNewVoucherNumberData : IEquatable<Model8APITransactionsNewVoucherNumberData>
    { 
        /// <summary>
        /// Gets or Sets VoucherType
        /// </summary>
        [DataMember(Name="VoucherType")]
        public string VoucherType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Model8APITransactionsNewVoucherNumberData {\n");
            sb.Append("  VoucherType: ").Append(VoucherType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Model8APITransactionsNewVoucherNumberData)obj);
        }

        /// <summary>
        /// Returns true if Model8APITransactionsNewVoucherNumberData instances are equal
        /// </summary>
        /// <param name="other">Instance of Model8APITransactionsNewVoucherNumberData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Model8APITransactionsNewVoucherNumberData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VoucherType == other.VoucherType ||
                    VoucherType != null &&
                    VoucherType.Equals(other.VoucherType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VoucherType != null)
                    hashCode = hashCode * 59 + VoucherType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Model8APITransactionsNewVoucherNumberData left, Model8APITransactionsNewVoucherNumberData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Model8APITransactionsNewVoucherNumberData left, Model8APITransactionsNewVoucherNumberData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
